INSERT INTO User(FIRST_NAME,LAST_NAME)
VALUES ('Mark','JR');
INSERT INTO User(FIRST_NAME,LAST_NAME)
VALUES ('Golf','555');
INSERT INTO User(FIRST_NAME,LAST_NAME)
VALUES ('Sam','JR');
INSERT INTO User(FIRST_NAME,LAST_NAME)
VALUES ('Cat','555');
INSERT INTO User(FIRST_NAME,LAST_NAME)
VALUES ('Dog','JR');
INSERT INTO User(FIRST_NAME,LAST_NAME)
VALUES ('Jame','555');
INSERT INTO User(FIRST_NAME,LAST_NAME)
VALUES ('Dome','JR');
INSERT INTO User(FIRST_NAME,LAST_NAME)
VALUES ('Ice','555');